export enum ContentType {
	JSON = "application/json",
	HTML = "text/html",
	TEXT = "text/plain",
	XML = "application/xml",
	FORM_URLENCODED = "application/x-www-form-urlencoded",
	FORM_DATA = "multipart/form-data",
	JAVASCRIPT = "application/javascript",
	CSS = "text/css",
	CSV = "text/csv",
	PNG = "image/png",
	JPEG = "image/jpeg",
	GIF = "image/gif",
	BMP = "image/bmp",
	WEBP = "image/webp",
	SVG = "image/svg+xml",
	PDF = "application/pdf",
	ZIP = "application/zip",
	GZIP = "application/gzip",
}
